const nextoSelectors = {
  
  urlLogin: 'https://nextocasino.com/?modal=login',
  urlRegistration: 'https://nextocasino.com/casino/live_casino?modal=register', 
  baseUrl: 'https://nextocasino.com',
  searchButton: 'button[class="relative w-full"]',  // Selector for the search button
  searchInput: 'input[placeholder="Search"]',  // Selector for the search input field
  gameResultContainer: '.flex.items-stretch.space-x-1.flex-1.sm\\:p-4.overflow-auto',  // Selector for the container of game results
  gameNameSelector: 'div.text-color-b.text-sm.md\\:text-base.font-medium.truncate',  // Selector for game names inside the container
  noResultsMessage: '.cursor-default.select-none.relative.text-color-b.text-center',  // Selector for the "No results" message
  providerFilter: '.flex-shrink-0.md\\:w-52',  // Selector for the provider filter section
  providerName: 'div.text-color-e',  // Selector for the provider name
  providerCheckbox: 'input[type="checkbox"]',  // Selector for the checkbox inside the provider label


  norway_providers: [
    { name: '1X2', expectedName: 'ONE_X_TWO' },
    { name: 'Amatic' },
    { name: 'Apollo' },
    { name: 'Arcadem' },
    { name: 'Arrows Edge', expectedName: 'ARROWS_EDGE' },
    { name: 'Atmosfera' },
    { name: 'Atomic Slot Lab' },
    { name: 'Avatar Ux' },
    { name: 'BGaming' },
    { name: 'Belatra' },
    { name: 'Betgamestv' },
    { name: 'Betsoft' },
    { name: 'Betsolutions' },
    { name: 'Blue Guru' },
    { name: 'Booming' },
    { name: 'CT Interactive', expectedName: 'CT_GAMING' },
    { name: 'Caleta' },
    { name: 'Dragongaming' },
    { name: 'Eeze' },
    { name: 'Endorphina' },
    { name: 'Espresso Games' },
    { name: 'Eurasian gaming', expectedName: 'EAGAMING' },
    { name: 'Evoplay' },
    { name: 'Fazi' },
    { name: 'Felix Gaming', expectedName: 'FELIX' },
    { name: 'Fugaso' },
    { name: 'Funky Games' },
    { name: 'Gameart' },
    { name: 'Gamebeat' },
    { name: 'Games Inc', expectedName: 'GAMESINC' },
    { name: 'Gamomat' },
    { name: 'Givme' },
    { name: 'Habanero' },
    { name: 'Inbet' },
    { name: 'Irondog' },
    { name: 'KA gaming', expectedName: 'KAGAMING' },
    { name: 'Kalamba' },
    { name: 'Kiron' },
    { name: 'Leap gaming' },
    { name: 'Liw' },
    { name: 'Lucky Streak' },
    { name: 'Mancala' },
    { name: 'Mascot' },
    { name: 'Medialive' },
    { name: 'Merkur' },
    { name: 'MrSlotty', expectedName: 'MR_SLOTTY' },
    { name: 'Netent' },
    { name: 'Netgaming' },
    { name: 'Nolimit' },
    { name: 'Novomatic' },
    { name: 'Nucleus', expectedName: 'NUCLEOUS' },
    { name: 'Octoplay' },
    { name: 'One Spin For Win' },
    { name: 'Onetouch' },
    { name: 'Oryx' },
    { name: 'PG Soft', expectedName: 'PGSOFT' },
    { name: 'Platipus' },
    { name: 'Play N Go' },
    { name: 'Playson' },
    { name: 'Playstar' },
    { name: 'Playtech' },
    { name: 'Quickspin' },
    { name: 'Red Rake' },
    { name: 'Rogue' },
    { name: 'Rubyplay' },
    { name: 'Sagaming' },
    { name: 'Saucify', expectedName: 'GENII' },
    { name: 'Smartsoft' },
    { name: 'Spadegaming' },
    { name: 'Spearhead' },
    { name: 'Spinmatic' },
    { name: 'Spinomenal' },
    { name: 'Spribe' },
    { name: 'Superlotto' },
    { name: 'TPG' },
    { name: 'Tom horn', expectedName: 'TOMHORN' },
    { name: 'Tvbet' },
    { name: 'Vivo' },
    { name: 'Wazdan' },
    { name: 'Yggdrasil' },
    { name: 'Zeus Play' },
    { name: 'Zillion' },
  ],

  norway_excluded_providers: [
    { name: 'System' },
    { name: 'Trustly' },
    // { name: 'Wazdan' },
    // { name: 'Yggdrasil' },
    // { name: 'Zeus Play' },
    // { name: 'Zillion' },
  ],

  germany_providers: [
    { name: '1X2', expectedName: 'ONE_X_TWO' },
    { name: 'Amatic' },
    { name: 'Apollo' },
    { name: 'Arcadem' },
    { name: 'Arrows Edge', expectedName: 'ARROWS_EDGE' },
    { name: 'Atmosfera' },
    { name: 'Atomic Slot Lab' },
    { name: 'Avatar Ux' },
    { name: 'BGaming' },
    { name: 'Belatra' },
    { name: 'Betgamestv' },
    { name: 'Betsoft' },
    { name: 'Betsolutions' },
    { name: 'Blue Guru' },
    { name: 'Booming' },
    { name: 'CT Interactive', expectedName: 'CT_GAMING' },
    { name: 'Caleta' },
    { name: 'Dragongaming' },
    { name: 'Eeze' },
    { name: 'Endorphina' },
    { name: 'Espresso Games' },
    { name: 'Eurasian gaming', expectedName: 'EAGAMING' },
    { name: 'Evoplay' },
    { name: 'Felix Gaming', expectedName: 'FELIX' },
    { name: 'Fugaso' },
    { name: 'Funky Games' },
    { name: 'Gameart' },
    { name: 'Gamebeat' },
    { name: 'Games Inc', expectedName: 'GAMESINC' },
    { name: 'Gamomat' },
    { name: 'Givme' },
    { name: 'Habanero' },
    { name: 'Inbet' },
    { name: 'Irondog' },
    { name: 'KA gaming', expectedName: 'KAGAMING' },
    { name: 'Kalamba' },
    { name: 'Kiron' },
    { name: 'Leap gaming' },
    { name: 'Liw' },
    { name: 'Lucky Streak' },
    { name: 'Mancala' },
    { name: 'Mascot' },
    { name: 'Medialive' },
    { name: 'MrSlotty', expectedName: 'MR_SLOTTY' },
    { name: 'Netent' },
    { name: 'Netgaming' },
    { name: 'Nolimit' },
    { name: 'Novomatic' },
    { name: 'Nucleus', expectedName: 'NUCLEOUS' },
    { name: 'Octoplay' },
    { name: 'One Spin For Win' },
    { name: 'Onetouch' },
    { name: 'Oryx' },
    { name: 'PG Soft', expectedName: 'PGSOFT' },
    { name: 'Platipus' },
    { name: 'Play N Go' },
    { name: 'Playson' },
    { name: 'Playstar' },
    { name: 'Playtech' },
    { name: 'Quickspin' },
    { name: 'Red Rake' },
    { name: 'Rogue' },
    { name: 'Rubyplay' },
    { name: 'Sagaming' },
    { name: 'Saucify', expectedName: 'GENII' },
    { name: 'Smartsoft' },
    { name: 'Spadegaming' },
    { name: 'Spearhead' },
    { name: 'Spinmatic' },
    { name: 'Spinomenal' },
    { name: 'Spribe' },
    { name: 'Superlotto' },
    { name: 'TPG' },
    { name: 'Tom horn', expectedName: 'TOMHORN' },
    { name: 'Tvbet' },
    { name: 'Vivo' },
    { name: 'Wazdan' },
    { name: 'Yggdrasil' },
    { name: 'Zeus Play' },
    { name: 'Zillion' },
  ],

  // germany_excluded_providers: [
  //   { name: 'System' },
  //   { name: 'Trustly' },
  //   { name: 'Acme payments' },
  //   { name: 'Alphapo' },
  //   { name: 'Altenar v 2' },
  //   { name: 'Aps' },
  //   { name: 'Arrows edge' },
    // { name: 'Astropay' },
    // { name: 'Astroplay' },
    // { name: 'Banks' },
    // { name: 'Banky' },
    // { name: 'Betby' },
    // { name: 'Bfgames' },
    // { name: 'Booongo' },
    // { name: 'Brite' },
    // { name: 'Cardpaymentz' },
    // { name: 'Cashlib' },
    // { name: 'Cashtocode' },
    // { name: 'Checkout' },
    // { name: 'Citizen' },
    // { name: 'Coindirect' },
    // { name: 'Coinspaid' },
    // { name: 'Cryptopay' },
    // { name: 'Delasport' },
    // { name: 'Dimoco' },
    // { name: 'Directa 24' },
    // { name: 'Eupaymentz' },
  // ],
  



};





export default nextoSelectors;
